[2024-06-02T19:17:15.023+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T19:17:15.034+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipline_v1.load_model_task manual__2024-06-02T19:16:53.594532+00:00 [queued]>
[2024-06-02T19:17:15.037+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipline_v1.load_model_task manual__2024-06-02T19:16:53.594532+00:00 [queued]>
[2024-06-02T19:17:15.037+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-02T19:17:15.042+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_model_task> on 2024-06-02 19:16:53.594532+00:00
[2024-06-02T19:17:15.050+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=165) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-02T19:17:15.051+0000] {standard_task_runner.py:63} INFO - Started process 175 to run task
[2024-06-02T19:17:15.051+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipline_v1', 'load_model_task', 'manual__2024-06-02T19:16:53.594532+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpnm0gfau5']
[2024-06-02T19:17:15.053+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask load_model_task
[2024-06-02T19:17:15.117+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipline_v1.load_model_task manual__2024-06-02T19:16:53.594532+00:00 [running]> on host 5c4500cfcd77
[2024-06-02T19:17:15.201+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='brijesh' AIRFLOW_CTX_DAG_ID='data_pipline_v1' AIRFLOW_CTX_TASK_ID='load_model_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T19:16:53.594532+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-02T19:16:53.594532+00:00'
[2024-06-02T19:17:15.203+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T19:17:15.222+0000] {logging_mixin.py:188} INFO - Optimal no. of clusters: 8
[2024-06-02T19:17:15.224+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but KMeans was fitted without feature names
  warnings.warn(

[2024-06-02T19:17:15.254+0000] {python.py:237} INFO - Done. Returned value was: 5
[2024-06-02T19:17:15.266+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T19:17:15.315+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_pipline_v1, task_id=load_model_task, run_id=manual__2024-06-02T19:16:53.594532+00:00, execution_date=20240602T191653, start_date=20240602T191715, end_date=20240602T191715
[2024-06-02T19:17:15.336+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-02T19:17:15.345+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T19:17:15.346+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
