[2024-06-06T22:07:39.833+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T22:07:39.876+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipline_v2.handle_comments manual__2024-06-06T22:07:25.030680+00:00 [queued]>
[2024-06-06T22:07:39.897+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipline_v2.handle_comments manual__2024-06-06T22:07:25.030680+00:00 [queued]>
[2024-06-06T22:07:39.899+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-06T22:07:39.936+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): handle_comments> on 2024-06-06 22:07:25.030680+00:00
[2024-06-06T22:07:39.949+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=74) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-06T22:07:39.954+0000] {standard_task_runner.py:63} INFO - Started process 76 to run task
[2024-06-06T22:07:39.952+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipline_v2', 'handle_comments', 'manual__2024-06-06T22:07:25.030680+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpnu6d06qi']
[2024-06-06T22:07:39.956+0000] {standard_task_runner.py:91} INFO - Job 52: Subtask handle_comments
[2024-06-06T22:07:39.982+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-06T22:07:40.053+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipline_v2.handle_comments manual__2024-06-06T22:07:25.030680+00:00 [running]> on host be153ff008c0
[2024-06-06T22:07:40.265+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sanket' AIRFLOW_CTX_DAG_ID='data_pipline_v2' AIRFLOW_CTX_TASK_ID='handle_comments' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T22:07:25.030680+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-06T22:07:25.030680+00:00'
[2024-06-06T22:07:40.269+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T22:07:40.271+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T22:07:40.272+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/src/data_preprocessing/handle_comments.py", line 11, in remove_comments
    lines = code.split('\n')
            ^^^^^^^^^^
AttributeError: 'list' object has no attribute 'split'
[2024-06-06T22:07:40.319+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_pipline_v2, task_id=handle_comments, run_id=manual__2024-06-06T22:07:25.030680+00:00, execution_date=20240606T220725, start_date=20240606T220739, end_date=20240606T220740
[2024-06-06T22:07:40.359+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 52 for task handle_comments ('list' object has no attribute 'split'; 76)
[2024-06-06T22:07:40.413+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-06T22:07:40.447+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-06T22:07:40.454+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
